S03US09 BIEN EN AVANT SUR PAGE ACCUEIL
WildCodeSchool/orleans-php-202103-project-clubimmo pull request #104
Opened 2021-04-28 15:53 UTC by jfillion12394

Triple carousel de présentation des biens à mettre en avant sur la page d'accueil

2021-04-28 16:03 UTC, jaldabaoth-code commented
il est pas passé ton push, il faut refaire

2021-04-29 05:54 UTC, jaldabaoth-code reviewed
le fond gris pour les prix je ferais en violet, sinon t'es requêtes sont a revoir en groupe je pense

2021-04-29 05:54 UTC, jaldabaoth-code commented on src/Controller/HomeController.php
> +    public function getPicsLeftSlider(): int
je comprend pas très bien a  quoi sert les get qui return des 1, 2 ou 3

2021-04-29 07:22 UTC, jfillion12394 commented on src/Controller/HomeController.php
> +    public function getPicsLeftSlider(): int
c'est les id des 3 biens à mettre en avant dans chaque carousel.  Les admin peuvent décider quels biens mettre en avant et ça peut être stocké dans ma bd. 
Sinon on peut déciser d'afficher les 3 dcerniers biens saisis... je ne sais pas ce qyui est mieux. A discuter.

2021-04-29 13:28 UTC, jaldabaoth-code commented on src/View/Home/Carousel/_carousel1.html.twig
> +<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
pour moi t'es pas obligé d'avoir 3 fichiers qui font la même chose tu peux en avoir qu'un

2021-04-29 13:28 UTC, jaldabaoth-code commented on src/View/Home/goodDealsPics.html.twig
> +                    <div class="col-lg-4 p-2 card d-md-block">
donc ici aussi t'es pas obligé de répéter la même chose 3 fois, mais si tu supprimes tes 2 autres fichiers ca devrait être bon ici aussi

2021-04-29 13:28 UTC, jaldabaoth-code commented on src/View/Home/index.html.twig
>      {% endblock %}
include avec des _ dans les noms, et tes pas obligé de faire un block pour chaque include

2021-04-29 13:28 UTC, jaldabaoth-code commented on src/Controller/HomeController.php
> +        $photos2 = $photoManager->selectByPropertyId($this->getPicsMidSlider()); //middle carousel pics
pour cette partie je suis pas sure de moi mais je pense qu'il doit y avoir un moyen plus facile pour faire ca, sans que tu sois obliger de créer selectByPropertyId

2021-04-29 13:28 UTC, jaldabaoth-code commented on src/Model/HomeCarouselManager.php
>  {
je comprend pas a quoi ca te sert cette table

2021-04-29 13:44 UTC, jfillion12394 commented on src/View/Home/goodDealsPics.html.twig
> +                    <div class="col-lg-4 p-2 card d-md-block">
trop compliqué pour.... sais pas commen,t faire

2021-04-29 13:45 UTC, jfillion12394 commented on src/View/Home/Carousel/_carousel1.html.twig
> +<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
ai testé, ça marche pas

2021-05-03 05:46 UTC, jaldabaoth-code commented
_carousel.html.twig doit etre dans home, pour le reste ca me va

2021-05-03 10:24 UTC, jaldabaoth-code approved these changes, later dismissed

2021-05-03 16:27 UTC, JuMn88 submitted a review, later dismissed

2021-05-03 21:55 UTC, sblondeau requested changes
je ne te fais pas plus de commentaires car je ne suis pas sur de ce que tu veux mettre dans ton slider. On ajustera quand tu m'auras expliqué ;-)

2021-05-03 21:55 UTC, sblondeau commented on HomeCarrousel.sql
> +CREATE TABLE `photo` (
pourquoi c'est pas dans db.sql ?
il me faut un seul fichier avec tout le sql dedans

2021-05-03 21:55 UTC, sblondeau commented on db.sql
> +CREATE TABLE `bien` (
attention, les noms de tables doivent etre en anglais ! à renommer

2021-05-03 21:55 UTC, sblondeau commented on db.sql
> +CREATE TABLE `bien` (
idem pour tous les champs en dessous d'ailleurs

2021-05-03 21:55 UTC, sblondeau commented on src/Controller/HomeController.php
> +        foreach ($photoManager->selectLastProperties() as $value) {
non, ta boucles n'est pas bien ecrite. Si tu veux farie ça, c'est 
```
foreach ($photoManager->selectLastProperties() as $index=>$property) {
            $photos[$index] = $photoManager->selectByPropertyId($value["ID"]);
            // ...
}
```
mais en réalité je ne pense pas que tu veuilles récupérer toutes les photos des biens ? juste une par bien peut-etre, la principale? vous gérer comment l'image sur les vignettes de maison normalement ?
Tu pourrais récup ce qui t'intéresse via une jointure et seulement envoyer le résultats à ta vue

2021-05-03 21:55 UTC, sblondeau commented on src/Model/PhotoManager.php
> +        $query .= 'INNER JOIN property PR ON PH.PROPERTY_ID = PR.ID  ';
n'écris pas les noms de champs/table en majuscule, uniquement les mots clés de SQL. Ca améliore la lisibilité

2021-05-03 21:55 UTC, sblondeau commented on src/Model/PropertyManager.php
> +    public function selectHomeSliderInfo(int $id)
là tu fais une jointure, mais je ne suis pas sur que tu aies besoin de toutes ces infos pour un slider si ?
dans tous les cas, tu devrais réutiliser les constantes TABLE de chaque Manager plutot que de réécrire les noms de table "en dur"

2021-05-04 09:45 UTC, jfillion12394 commented on src/Controller/HomeController.php
> +        foreach ($photoManager->selectLastProperties() as $value) {
L'idée telle que je la conçoit est 
- d'afficher 3 diaporamas côte à côte, et chaque diapo montre les photos (2 ou 3 part diapo) d'un bien mis en avant.
- ces 3 diaporamas correspondent aux 3 derniers biens saisis en base.

Du coup effectivement  avec la fonction selectLastProperties() je récupère les ids des 3 derniers biens saisis.
Et à chaque tour de boucle je vais remlir 2 tableaux:
1) $photos : dans lequel je stocke les photos des 3 derniers biens saisis
2) $properties: ou je stocke les informations à faire apparaître dans les cartes contenant les diapos : type bies, secteur, prix.
j'ai donc besoin de récupérer plusieurs (2 à 3) photos par bien/diaporama, qu'en penses-tu?
Je vais refaire la boucle selon tes conseils.

2021-05-04 10:08 UTC, jfillion12394 commented on src/Model/PropertyManager.php
> +    public function selectHomeSliderInfo(int $id)
vue que nous avons mis les  biens dans une table "property", les secteurs (quartiers) dans un table "sector" et les types de biens (maisons, appart, etc.) dans un table "propertyType", je dois faire une jointure entre ces différentes tables pour reconstituer l'information: chaque bien avec  son type de bien et sa localisation.

Par contre effectivement, j'ai mes des tables en dur. Je vais voir pour faire autrement

2021-05-04 13:22 UTC, JuMn88 approved these changes

2021-05-04 14:09 UTC, jaldabaoth-code approved these changes

2021-05-04 14:34 UTC, sblondeau approved these changes

2021-05-04 14:34 UTC, merged