S04 us20 admin upload
WildCodeSchool/orleans-php-202103-project-clubimmo pull request #123
Opened 2021-05-02 16:45 UTC by JuMn88

-Adding an upload input in the admin form
-Securing the input file
-Extending the db insertion to every input

2021-05-03 08:17 UTC, jfillion12394 commented on src/Controller/AdminAdvertisementController.php
> +        //var_dump($_FILES); die;
penser à retirer les commentaires de debug

2021-05-03 08:17 UTC, jfillion12394 submitted a review, later dismissed

2021-05-03 10:02 UTC, Thuydieutran approved these changes, later dismissed

2021-05-03 14:38 UTC, sblondeau approved these changes

2021-05-03 14:39 UTC, sblondeau requested changes

2021-05-03 14:39 UTC, sblondeau commented on src/Controller/AdminAdvertisementController.php
> +        //var_dump($_FILES); die;
ah oui pas de code commenté, bien vu !

2021-05-04 06:55 UTC, Thuydieutran approved these changes, later dismissed

2021-05-04 13:11 UTC, jfillion12394 submitted a review, later dismissed

2021-05-04 14:39 UTC, sblondeau approved these changes, later dismissed

2021-05-04 15:07 UTC, jaldabaoth-code approved these changes

2021-05-04 15:41 UTC, jfillion12394 approved these changes

2021-05-04 16:02 UTC, merged