S03 us12 search bar
WildCodeSchool/orleans-php-202103-project-clubimmo pull request #129
Opened 2021-05-03 08:50 UTC by Thuydieutran

2021-05-03 09:59 UTC, sblondeau requested changes

2021-05-03 09:59 UTC, sblondeau commented on src/Controller/PropertyController.php
> +            if ($searchType['propertyType']!=""){
je pense que ces conditions sont inutiles ? 
par contre il faut que tu es une gestion des erreurs comme pour un form en POST
donc une méthode validate (par exemple verifier si le prix est bien un numérique > 0), que les valeurs choisies dans les select font bien partie des valeurs autorisées, etc

2021-05-03 09:59 UTC, sblondeau commented on src/Controller/PropertyController.php
> +            'properties' => $properties,
as ta vue, tu dois 
- envoyer les données de la database qui te servent à construire des "select" (donc propertyTypes, sectors). Pour les transactions, si c'est pas en BDD utilise la constante définie plus haut (tu peux passer une variable transaction**s** à ta vue)
- envoyer une variable 'search' qui contient $searchType (ça va te servir justement à remplier les "value" de tes champs et donc ne pas avoir tout le temps des champs de form qui se vident
- envoyer ton tableau d'erreur.
donc je pense que propertyTypeId, sectorId, transaction et budget sont inutile

2021-05-03 09:59 UTC, sblondeau commented on src/Model/PropertyManager.php
> +            if (!empty($conditions)) {
si tu fais une méthode comme ça, elle devrait etre private et non public

de plus, c'est pas très optimisé ton " AND " avec la condition. Ca serait mieux par ex de renvoyer un tableau, et à la fin tu fais un implode(" AND ", $queryParts) pour ajouter tes AND au milieu.

2021-05-03 09:59 UTC, sblondeau commented on src/View/Property/index.html.twig
> +  <form class="container col-lg-9 my-5 text-purple pt-5 pb-3" action="/property/index/" method="GET">
comme discuté, ajoute des label et utilise les placeholder pour mettre des exemples

2021-05-05 00:48 UTC, jaldabaoth-code submitted a review, later dismissed

2021-05-05 07:22 UTC, jfillion12394 submitted a review, later dismissed

2021-05-05 07:32 UTC, sblondeau approved these changes

2021-05-05 07:32 UTC, sblondeau commented on property.sql
> +/* CREATE TABLES AND INSERT FOR TEST */
vous ne devez avoir qu'un seul fichier sql, donc mets tout dans database.sql

2021-05-05 07:33 UTC, sblondeau requested changes
mieux dans l'ensemble, il resterait des choses à optimiser mais on va passer comme ça dès que tu auras fusionné les sql

2021-05-05 08:20 UTC, jfillion12394 approved these changes

2021-05-05 08:21 UTC, jaldabaoth-code approved these changes

2021-05-05 08:21 UTC, sblondeau approved these changes

2021-05-05 08:21 UTC, merged