S03 us19 advertisement contact
WildCodeSchool/orleans-php-202103-project-clubimmo pull request #130
Opened 2021-05-03 09:43 UTC by jaldabaoth-code

2021-05-03 10:06 UTC, JuMn88 approved these changes, later dismissed

2021-05-03 10:08 UTC, jfillion12394 submitted a review, later dismissed

2021-05-03 14:46 UTC, sblondeau requested changes

2021-05-03 14:46 UTC, sblondeau commented on src/Controller/ContactController.php
> +                $mailPart1 = "";
dans l'ensemble la gestion de mail semble pas mal. Juste cette partie qui ne va pas.
Quand tu envoies un mail, tu créés une vue (qui est ton mail) donc la construction de ce dernier doit se faire dans un fichier Twig. C'est juste qu'au lieu d'afficher cette vue Twig dans le navigateur en faisant un return, tu envoies cette vue Twig à ta méthode html() du mailer.

en gros tu fait un $emailBody = $this->twig->render('contact/email.html.twig', [$variable1, $variable2...])
et $email->...->html($emailBody);

2021-05-04 13:14 UTC, jfillion12394 approved these changes, later dismissed

2021-05-04 13:49 UTC, JuMn88 submitted a review, later dismissed

2021-05-04 14:40 UTC, sblondeau approved these changes, later dismissed

2021-05-04 15:01 UTC, JuMn88 approved these changes

2021-05-04 15:02 UTC, jfillion12394 approved these changes

2021-05-04 15:41 UTC, merged