S01 us01 footer
WildCodeSchool/orleans-php-202103-project-clubimmo pull request #22
Opened 2021-04-15 07:39 UTC by jfillion12394

2021-04-15 15:48 UTC, Thuydieutran approved these changes, later dismissed
c'est bon pour moi!

2021-04-15 15:57 UTC, JuMn88 submitted a review, later dismissed
Validé pour moi

2021-04-15 18:42 UTC, sblondeau requested changes

2021-04-15 18:42 UTC, sblondeau commented on src/View/Includes/_footer.html.twig
> + <footer class="text-center text-white" style="background-color: rgba(221, 221, 221, 0.55);">
pas de style en inline, faut le mettre dans le fichier CSS

2021-04-15 18:42 UTC, sblondeau commented on src/View/Includes/_footer.html.twig
> +        ><i class="fab fa-google-f"></i
à quoi te sert ce "fab fa-google-f" ?  tu as copier coller du code depuis un template peut-etre ? normalement c'est pour gérer des icones mais il faut installer une librairies appelée fontawesome. là tu n'as pas besoin de ça pour des liens "mentions légales" ou "honoraires"
de plus l'attribut data-mdb-ripple-color est inutile aussi, je ne sais pas d'où ça sort ?

2021-04-15 18:42 UTC, sblondeau commented on src/View/Includes/_footer.html.twig
> +{% extends 'layout.html.twig' %}
attention si ce fichier doit etre inclus dans un autre il ne faut pas qu'il étende layout, il faut juste que ce soit un bout de code HTML qui va venir s'inclure dans une autre page qui, elle, étendra layout

2021-04-16 08:18 UTC, JuMn88 submitted a review, later dismissed
Corrections done

2021-04-16 08:20 UTC, jaldabaoth-code submitted a review, later dismissed
bien

2021-04-16 08:33 UTC, sblondeau requested changes

2021-04-16 08:33 UTC, sblondeau commented on public/assets/css/style.css
> +    background-color: rgba(221, 221, 221, 0.55);
couleurs en variable CSS

2021-04-16 09:21 UTC, jaldabaoth-code approved these changes

2021-04-16 09:35 UTC, sblondeau approved these changes

2021-04-16 09:36 UTC, merged