S01 us01 header
WildCodeSchool/orleans-php-202103-project-clubimmo pull request #23
Opened 2021-04-15 09:40 UTC by jaldabaoth-code

creation de navbar et de header

2021-04-15 12:57 UTC, jfillion12394 approved these changes, later dismissed
Ok pour mpo

2021-04-15 15:00 UTC, Thuydieutran commented
good job!

2021-04-15 15:03 UTC, Thuydieutran approved these changes, later dismissed
good job!

2021-04-15 16:03 UTC, JuMn88 submitted a review, later dismissed
C'est bon.

2021-04-15 18:54 UTC, sblondeau requested changes

2021-04-15 18:54 UTC, sblondeau commented on config/db.php.dist
> +define('APP_DB_USER', 'mysql_zura');
le fichier .dist ne doit PAS etre modifié, c'est un modèle. Tu dois créer un db.php à partir de celui-ci (non versionné). Là tu viens de push tes identifiants en ligne :/

2021-04-15 18:54 UTC, sblondeau commented on public/assets/css/navbar.css
> +@media only screen and (max-width: 600px) {
tu ne devrais pas besoin de toutes ces media queries si tu utilises bien la navbar de base de bootstrap

2021-04-15 18:54 UTC, sblondeau commented on src/Controller/AnnonceController.php
> +class AnnonceController extends AbstractController
sauf erreur de ma part, Annonce n'est pas anglais, il faudrait plutot mettre "advertisement" je pense. Il faut tout renommer, dsl

2021-04-15 18:54 UTC, sblondeau commented on src/Controller/HomeController.php
> +    public function accueil()
idem, home et pas accueil => Nommage en anglais ;-)

2021-04-15 18:54 UTC, sblondeau commented on src/Controller/AnnonceController.php
> +class AnnonceController extends AbstractController
de plus, si ta US c'est faire le header, la partie Annonce n'a rien à faire dans cette PR de toute manière, à enlever

2021-04-15 18:54 UTC, sblondeau commented on src/Controller/HomeController.php
> +    public function accueil()
mais à la réflexion, tu as déjà une methode index, elle est suffisante, je comprend pas trop pourquoi tu créé accueil en plus, ni pourquoi dans le return de index() tu lui concatène $this->accueil(), à revoir

2021-04-15 18:54 UTC, sblondeau commented on src/View/Annonce/annonce.html.twig
> +{% extends 'layout.html.twig' %}
les annonces, c'est pour une autre US

2021-04-15 18:54 UTC, sblondeau commented on src/View/Annonce/carousel.html.twig
> +<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="an
et du coup je pense que ce carousel est en trop aussi puisqu'il semble attaché à la partie annonce.

Si ta US est "faire le header", ça sous entend le header de la page d'accueil, pas tous les header différents de toutes les pages ;-) => retire ça de la PR également

2021-04-15 18:54 UTC, sblondeau commented on src/View/Home/accueil.html.twig
> +
met se code dans le fichier Home/index.html.twig déjà existant comme vu plus haut
je ne suis pas sur que tu es besoin de crée un block header ici ?

2021-04-15 18:54 UTC, sblondeau commented on src/View/Home/header.html.twig
> +                        <input type="search" id="form1" class="form-control" placeholder="Type query" aria-label="Search" />
le placeholder est "type query" or ça devrait etre du français là pour le coup  (à modifier à plusieurs endroits)

2021-04-15 18:54 UTC, sblondeau commented on src/View/Home/header.html.twig
> +                        <input type="search" id="form1" class="form-control" placeholder="Type query" aria-label="Search" />
de plus, je ne comprend pas trop ce que tu essaie de faire, tu as plusieurs fois des input identiques avec un bouton RECHERCHER, y a peut-etre qq chose qui m'échappe

2021-04-16 07:57 UTC, JuMn88 approved these changes
Corrections done

2021-04-16 07:58 UTC, Thuydieutran approved these changes
Good for me!

2021-04-16 08:42 UTC, sblondeau requested changes

2021-04-16 08:42 UTC, sblondeau commented on public/assets/css/header.css
> +    background-color: rgba(162, 0, 255, 0.397);
couleur en variable css

2021-04-16 08:42 UTC, sblondeau commented on public/assets/css/header.css
> +    .header_title{
ça c'est gérable avec des classes d-xx-none par ex

2021-04-16 08:42 UTC, sblondeau commented on public/assets/css/header.css
> +    .nav-item .nav-link {
tu ne devrais pas modifier la taille de la police de cette manière, j'ai peur que ça devienne illisible sur petit écran

2021-04-16 08:42 UTC, sblondeau commented on src/View/Home/header.html.twig
> +        <div class="tab-content" id="myTabContent">
ça ne va pas là vous répétez 2 fois le meme form.
si vous souhaitez passer l'information "LOUER" ou "ACHETER" ça serait plutot via un bouton radio => et ça tombe bien bootstrap vous permet d'en créer qui sont stylisé pour ressembler à des "boutons" comme vous les avez fait là https://getbootstrap.com/docs/5.0/forms/checks-radios/#radio-toggle-buttons

ainsi vous n'avez qu'un seul form c'est plus simple, et vous pouvez tjs récupérer l'information dont vous avez besoin, à savoir si la recherche est pour louer ou acheter.

Après mon problème là c'est que vous me crééz un form qui n'est pas foncitonnel, y a pas de traitement, de validation serveur etc... 

L'idéal serait de reporter ça dans une autre US
- 1ere US : je fais un header (et je mets pas le form de recherche, meme si ça fait un peu vide)
- 2eme US: j'ajoute un form de recherche mais aussi le traitement qui me renvoie les résultats

2021-04-21 13:41 UTC, merged