S01 us05 page contact
WildCodeSchool/orleans-php-202103-project-clubimmo pull request #51
Opened 2021-04-19 09:46 UTC by Thuydieutran

2021-04-19 10:29 UTC, jaldabaoth-code submitted a review, later dismissed

2021-04-20 14:42 UTC, JuMn88 commented on src/View/Contact/index.html.twig
> +                            <option>Choissisez un type de bien</option>
Faute de frappe: choisissez. D'abord 1S puis 2S

2021-04-21 08:06 UTC, jaldabaoth-code submitted a review, later dismissed

2021-04-21 08:14 UTC, jfillion12394 submitted a review, later dismissed

2021-04-21 08:14 UTC, jfillion12394 commented
ok pour moi

2021-04-21 13:46 UTC, sblondeau requested changes
Tu fais trop compliqué, il faut que tu t'appuies beaucoup plus sur les classes de bootstrap

2021-04-21 13:46 UTC, sblondeau commented on src/View/Contact/index.html.twig
> +            <div class="row-form">
tu fais trop compliqué je trouve coté style de ton form
bootstrap a déjà plein de classes dédiées à la stylisation des form, utilise les classes par défaut. Tu peux simplifier grandement ton fichier CSS du coup

2021-04-21 13:46 UTC, sblondeau commented on src/View/Contact/index.html.twig
> +                <p><a href="#" id="show-hiddenForm" onclick="myFunction()"><strong>Cliquez ici</strong></a></p>
pareil pour cette partie, utilise le composant collapse de bootstrap qui fait la meme chose plutot que d'écrire ta propre fonction JS

https://getbootstrap.com/docs/5.0/components/collapse/

2021-04-22 05:52 UTC, jaldabaoth-code reviewed
-la navbar est superposé sur ton formulaire.
-comme la navbar est déjà ajouté ca serai bien si tu pouvais placer le lien de ton formulaire dans la navbar.

-pour ton code c'est bon pour moi.

2021-04-22 08:56 UTC, jaldabaoth-code submitted a review, later dismissed

2021-04-22 09:26 UTC, jfillion12394 submitted a review, later dismissed

2021-04-22 09:26 UTC, jfillion12394 commented
ok

2021-04-22 09:27 UTC, jaldabaoth-code approved these changes, later dismissed

2021-04-22 09:45 UTC, sblondeau requested changes

2021-04-22 09:45 UTC, sblondeau commented on src/Controller/ContactController.php
> +        return $this->twig->render('Contact/index.html.twig');
le form de contact devra à terme envoyer des emails, pour le moment vous ne l'avez pas vu donc exceptionnellement tu peux ne pas traiter cette partie dans la US. Par contre, tu dois quand meme faire la partie verification coté serveur ! (champs required, format email, ...), affichage des erreurs et une redirection si pas d'erreur.

2021-04-23 15:30 UTC, JuMn88 requested changes
Quelques modifications à faire dans les noms de ta base de données et quelques coquilles à corriger.
Dans l'ensemble c'est bon.

2021-04-23 15:30 UTC, JuMn88 commented on src/Controller/ContactController.php
> +        "Autres"
Il vaut mieux mettre Autre au singulier, idem ligne 36

2021-04-23 15:30 UTC, JuMn88 commented on src/Controller/ContactController.php
> +            $lastnameLength = 80;
regroupe tes déclarations/affectations de variables de ce type  au début de ta méthode pour ne pas avoir à les rechercher si on a besoin de les modifier (idem $messageLength ligne 72)

2021-04-23 15:30 UTC, JuMn88 commented on src/Controller/ContactController.php
> +*/
Retire cette partie là si tu ne t'en sers pas

2021-04-23 15:30 UTC, JuMn88 commented on src/Controller/ContactController.php
> +                $errors[] = 'Votre numéro de téléphone est invalid';
invalid**e**
idem ligne 121

2021-04-23 15:30 UTC, JuMn88 commented on src/Controller/ContactController.php
> +            return $this->twig->render('Contact/validateForm.html.twig'); */
Retire cette partie également

2021-04-23 15:30 UTC, JuMn88 commented on client.sql
> +  residence varchar(255),
adress est plus parlant et zip code pour le code postal

2021-04-23 15:30 UTC, JuMn88 commented on client.sql
> +--
il y a un fichier database.sql, il vaut peut-être mieux n'avoir qu'un seul fichier sql avec toutes les informations.

2021-04-23 15:30 UTC, JuMn88 commented on src/Model/ContactManager.php
> +        $query1 = "(`firstname`, `lastname`, `phone`, `email`, `residence`,";
Comme dans la définition de ta base de données: adress et zip code plutôt que residence et postal code

2021-04-23 15:30 UTC, JuMn88 commented on src/View/Contact/index.html.twig
> +                    <p class="text-collapse">Vous êtes propriétaire et vous voulez déposez un dossier ?</p>
dépose**r**

2021-04-23 15:30 UTC, JuMn88 commented on src/View/Contact/index.html.twig
> +    #}
Tu peux retirer cette partie.

2021-04-26 09:07 UTC, jaldabaoth-code submitted a review, later dismissed

2021-04-26 09:20 UTC, jaldabaoth-code submitted a review, later dismissed

2021-04-26 17:43 UTC, JuMn88 requested changes
A voir avec le groupe mais je pense qu'il faut retirer les styles css de la page layout qui ne sont pas propres à toutes les pages du site.

2021-04-26 17:43 UTC, JuMn88 commented on src/View/layout.html.twig
> +    <link rel="stylesheet" href="/assets/css/contact.css">
Je pense qu'il ne faut pas mettre les fichiers css propres à une page (contact, agency, property) dans le layout mais les appeler dans leurs pages respectives pour éviter les conflits.

2021-04-27 13:14 UTC, JuMn88 approved these changes, later dismissed

2021-04-27 15:16 UTC, jaldabaoth-code submitted a review, later dismissed

2021-04-27 15:44 UTC, sblondeau requested changes
tu t'embete en fait à gérer ça en database, je serais plutot parti sur un envoie de mail (meme si pour le moment tu ne sais pas forcément comme faire, fais le reste)

2021-04-27 15:44 UTC, sblondeau commented on src/Controller/ContactController.php
> +    public function submitForm()
non tout ce code doit etre dans la methode index()  cette methode submitForm ne sert à rien puisqu'elle fini par afficher le fichie index.html.twig. Il faut fusionner ces deux methodes en une seule. Si tu as des erreurs elles s'affichent, sinon tu fais ton header Location vers /contact/index (ça ne doit pas etre commenté). De plus, je ne sais pas si c'est pertinent d'enregistrer les messages de contact en database, j'aurais plus vu un envoi de mail directement, ça simplifie les choses (à la place de ton insert()). On verra plus tard comment on fait ça ^^

2021-04-28 11:28 UTC, jaldabaoth-code approved these changes

2021-04-28 13:16 UTC, JuMn88 approved these changes

2021-04-28 14:04 UTC, sblondeau requested changes

2021-04-28 14:04 UTC, sblondeau commented on src/Controller/ContactController.php
> +    public const TOPIC = [
TOPIC**S**

2021-04-28 14:04 UTC, sblondeau commented on src/Controller/ContactController.php
> +    public const PROPERTY_TYPE = [
PROPERTY_TYPES

2021-04-28 14:04 UTC, sblondeau commented on src/Controller/ContactController.php
> +        if ($_SERVER['REQUEST_METHOD'] === 'POST') {
condition inutile ici, la methode validate() doit etre lancée à l'intérieur de cette condition dans la méthode index()

2021-04-28 14:04 UTC, sblondeau commented on src/Controller/ContactController.php
> +            return $this->twig->render('Contact/index.html.twig', [
non tu t'y prends mal sur le retrun de twig, il faut en mettre un seul.
```
if ($_SERVER['REQUEST_METHOD'] === 'POST') {       
    $errors = $this->validateForm($client);
     if (empty($errors)) { 
         // TODO send mail
         header('Location /laPageDeTonChoix )
    }
      return $this->twig->render('Contact/index.html.twig', [
          'topics' => self::TOPICS,
          'propertyTypes' => self::PROPERTY_TYPES,
      ]);
}
```
pas besoin de ta variable success pour l'instant. J'ai tapé le code rapidement, y a peut-etre des approximations mais dans l'idée c'est ce qu'il faut faire, je te laisse ajuster si besoin ;-)

2021-05-05 10:16 UTC, closed without merging