mise à jour fichiers accueil info agence sprint  2
WildCodeSchool/orleans-php-202103-project-clubimmo pull request #58
Opened 2021-04-19 16:56 UTC by jfillion12394

2021-04-21 08:52 UTC, jaldabaoth-code submitted a review, later dismissed

2021-04-21 09:13 UTC, Thuydieutran approved these changes, later dismissed

2021-04-21 13:51 UTC, sblondeau requested changes

2021-04-21 13:51 UTC, sblondeau commented on src/View/Home/infoAgence.html.twig
> +              <p class="fs-5"><b>VOTRE NOUVEL ESPACE IMMOBILIER</b></p>
je pense que tu peux définir la font-size par défaut sur tes "p" et/ou "li", ou meme par défaut sur ton body, plutot que de mettre fs-5 sur chaque ligne

2021-04-21 13:51 UTC, sblondeau commented on src/View/Home/infoAgence.html.twig
> +          <ul class="col-12">
col-12 est le comportement par défaut si tu ne mets rien, donc ne mets rien ;-)

2021-04-21 13:51 UTC, sblondeau commented on public/assets/css/agency.css
> +    @media only screen and (max-width: 600px) {
tu peux éviter cette media query avec l'utilisation de classes bootstrap comme d-none, pour l'image peut-etre des % ou min-width/min-height
bref, c'est évitable ;-)

2021-04-21 14:32 UTC, jfillion12394 commented on src/View/Home/infoAgence.html.twig
> +              <p class="fs-5"><b>VOTRE NOUVEL ESPACE IMMOBILIER</b></p>
ok

2021-04-21 14:32 UTC, jfillion12394 commented on src/View/Home/infoAgence.html.twig
> +          <ul class="col-12">
ok

2021-04-21 17:46 UTC, jfillion12394 commented
J'ai fait les modifs 
Cordialement

Joël

2021-04-22 06:09 UTC, jaldabaoth-code reviewed
t'as pas la dernière version de la branch dev, du coup il manque la navbar, header.

sinon ton code est déjà plus propre qu'avant mais, des paddings et margin sdans ton css tu peux aussi faire en bootsrap, donc le css tu peux encore simplifié.

2021-04-27 13:09 UTC, closed without merging