S02 us02 advertisement ges
WildCodeSchool/orleans-php-202103-project-clubimmo pull request #60
Opened 2021-04-20 20:54 UTC by jaldabaoth-code

2021-04-21 10:59 UTC, Thuydieutran approved these changes, later dismissed

2021-04-27 15:16 UTC, JuMn88 submitted a review, later dismissed

2021-04-28 08:02 UTC, jfillion12394 submitted a review, later dismissed

2021-04-28 11:23 UTC, sblondeau requested changes

2021-04-28 11:23 UTC, sblondeau commented on src/Controller/AdvertisementController.php
> +        if (!empty($_GET)) {
non tu ne dois pas passer par GET pour ça, mais par un paramètre dans ta route
pour acceder à une annonce, tu dois saisir l'URL /Advertisement/index/5 par ex, et non pas /Advertisement/index/?id=5

2021-04-28 11:23 UTC, sblondeau commented on src/Controller/PropertyController.php
>      public function index()
j'ai pas bien en tete la différence entre le PropertyController et l'AdverstisementController ? tu pourrais pas en avoir qu'un seul avec une methode index() qui liste tout et une métthode show($id) pour n'afficher qu'un seul bien ?

2021-04-28 11:23 UTC, sblondeau commented on src/View/Advertisement/index.html.twig
> +        {% block energyInformations %}
ce block est inutile non  ? quand tu fais un include tu n'es pas forcé de le mettre dans un block

2021-04-28 11:23 UTC, sblondeau commented on src/View/Property/index.html.twig
> +                  <a href="/Advertisement/index/?id={{ property.id }}" class="btn-property btn text-light">Voir l'annonce</a>
route à modifier suite à mes différentes remarques, au final /Property/show/{{property.id}} me paraît le mieux

2021-04-28 11:23 UTC, sblondeau commented on src/View/Property/index.html.twig
> +                  <a href="/Advertisement/index/?id={{ property.id }}" class="btn-property btn text-light">Voir l'annonce</a>
et Attention également, tu as une image qui fait plus de 200ko, à reduire stp

2021-04-28 13:56 UTC, JuMn88 requested changes

2021-04-28 13:56 UTC, JuMn88 commented on src/Controller/PropertyController.php
> +        }
Ta condition vérifie que la dernière partie de l'url (après property/show/) est un nombre non vide.
Si toutefois cela arrive, l'alternative ne devrait-elle pas être l'affichage d'une page erreur 404? En l'état tu affiches le détail d'une annonce qui n'a pas d'informations.

2021-04-28 19:57 UTC, Thuydieutran approved these changes, later dismissed

2021-04-28 20:16 UTC, jfillion12394 approved these changes, later dismissed

2021-04-29 07:13 UTC, sblondeau requested changes

2021-04-29 07:13 UTC, sblondeau commented on src/Controller/PropertyController.php
> +    public function show($idProperty)
type en int le $idProperty
tu devais pouvoir te passer du is_numeric en dessous du coup, et t'es pas obligé de t'mbêter à faire une 404 (mais si tu veux vraiment, faut que tu envoie un header('Location: 404.php');

2021-04-29 07:13 UTC, sblondeau commented on src/View/Advertisement/_energyInformations.html.twig
> +                    <img class="col-12 px-0" src="\assets\images\DPE.png" alt="dpe">
les chemins c'est avec des "/" normalement, pas des "\"

2021-04-29 08:10 UTC, jfillion12394 approved these changes

2021-04-29 08:14 UTC, Thuydieutran approved these changes

2021-04-29 09:26 UTC, sblondeau approved these changes

2021-04-29 10:12 UTC, JuMn88 approved these changes

2021-04-29 11:46 UTC, merged