S02 us08 admin page
WildCodeSchool/orleans-php-202103-project-clubimmo pull request #66
Opened 2021-04-22 16:42 UTC by JuMn88

Adding an Admin section with an index page displaying the list of ads and add page.

2021-04-22 21:56 UTC, jaldabaoth-code commented
le conflit a résoudre, de plus le y a des truks dans le css tu peux faire en bootsrap.
display:non -> d-none
aligne-middle,
width75% possible avec col 12 -> col9.

sinon ca me semble bien.

2021-04-23 08:17 UTC, jaldabaoth-code submitted a review, later dismissed

2021-04-23 08:18 UTC, jfillion12394 submitted a review, later dismissed

2021-04-23 08:29 UTC, sblondeau requested changes
dans l'ensemble le code est propre, par contre j'ai dans la meme US
index et add, or ce sont 2 US distinctes ! à redecouper en deux donc

2021-04-23 08:29 UTC, sblondeau commented on public/assets/css/admin_advertisement.css
> +body {
les modifs sur body, h1, btn-purple ou empty sont, je pense, communes à tout le site et devraient etre plutot dans style.css

2021-04-25 18:38 UTC, jaldabaoth-code commented
globalement je pense que c'est bon,
mais, sur la version mobile c'est normal que le titre "Liste des annonces" ne soit pas centré?
et la constante dans le controller MAX_FIELD_LENGTH tu l'utilises ou?

2021-04-26 08:40 UTC, jaldabaoth-code approved these changes

2021-04-26 14:38 UTC, Thuydieutran approved these changes

2021-04-27 07:05 UTC, sblondeau approved these changes

2021-04-27 07:05 UTC, merged