S02 us03 advertisement header
WildCodeSchool/orleans-php-202103-project-clubimmo pull request #94
Opened 2021-04-27 12:54 UTC by jaldabaoth-code

2021-04-27 13:43 UTC, JuMn88 requested changes

2021-04-27 13:43 UTC, JuMn88 commented on README.md
> +
tu as oublié de traduire les noms

2021-04-27 15:19 UTC, JuMn88 submitted a review, later dismissed

2021-04-28 07:59 UTC, jfillion12394 submitted a review, later dismissed

2021-04-28 11:25 UTC, sblondeau requested changes
une large partie de cette PR correspond à la meme chose que la PR précédente, ça ne va pas, tu as encore un soucis au niveau de tes tirages de branches je pense, ou alors tu dupliques du code inutile. 
Je ne devrais pas retrouver le meme code (et donc pour le coup les memes erreurs ;-)) d'une PR à l'autre

2021-04-29 13:38 UTC, JuMn88 submitted a review, later dismissed

2021-04-29 15:22 UTC, Thuydieutran submitted a review, later dismissed

2021-04-29 15:50 UTC, sblondeau requested changes
Cette PR est sensé m'ajouter "seulement" un header sur la page (je ne sais pas trop ce que tu entends par header d'ailleurs). Mais au final je devrais avoir un bout de twig, un bout de controller  avec un simple selectOneById ou qq chose d'approchant. donc 3-4 fichiers avec pas grand chose de modifié dedans,. Là j'ai énormément de code à relire qui n'a rien à voir avec la US, ça ne me va pas !

2021-04-30 07:03 UTC, sblondeau approved these changes

2021-04-30 07:04 UTC, merged